sonar.projectKey=mysiis-web-main
sonar.projectName=mysiis-web-main
sonar.projectVersion=1.0.0

# diisi dengan file/folder yang ingin discan jika lebih dari 1 maka gunakan "," sebagai pemisah
sonar.sources=./

# diisi dengan extensi yang ingin discan jika lebih dari 1 maka gunakan "," sebagai pemisah
sonar.inclusions=pages/**/*,features/**/*,components/**/*,utils/**/*
sonar.exclusions=coverage/**/*,__tests__/**/*,__mocks__/**/*,utils/api/__tests__/**/*,utils/functions/__tests__/**/*,features/planning/dashboard-microdemand/**/*,features/planning/dashboard-permit/**/*
#enable code coverage report
sonar.javascript.lcov.reportPaths=./coverage/lcov.info

sonar.dynamicAnalysis=reuseReports
